246 remove cxf
eclipse-ee4j/krazo pull request #247
Opened 2021-04-12 19:37 UTC by erdlet

Removes CXF module + workarounds in the Core module.

Also...

- ... adapts the documentation
- ... removes TomEE from TCK / Testsuite profiles
- ... comments out OpenLiberty profile / adapts TCK Archive creation for later usage

In Jenkins, I disabled the TCK job for openliberty, so it won't fail because of the missing CXF dependency (it was red all the time, so I think that won't hurt us).

2021-04-12 20:05 UTC, lefloh approved these changes

2021-04-13 06:03 UTC, ivargrimstad requested changes
Latest versions of OpenLiberty 21.* comes with RESTEasy, so we should keep those tests in. Even if the tests fail currently, but I think that is more of a setup issue.

2021-04-13 06:03 UTC, ivargrimstad commented on tck/pom.xml
> +<!--         <profile> -->
Uncomment

2021-04-13 06:03 UTC, ivargrimstad commented on testsuite/pom.xml
> +<!--         <profile> -->
Uncomment

2021-04-13 10:12 UTC, erdlet commented
@ivargrimstad Thanks for your review. I've uncomment the Liberty configs and fixed the documentation. Also I re-enabled the TCK job and extended the testsuite job, so we can see if everything works when we use OpenLiberty with Krazo RESTEasy.

2021-04-13 11:24 UTC, ivargrimstad commented
Great!

The Jobs are set up since a while back in our Jenkins: https://ci.eclipse.org/krazo/ 

The EE4J GitHub organization is too big to be useful for Travis other than just doing the simple compile and run unit tests. One spin of our TCK exhausted all the resources so it was useless for 24 hours :)

2021-04-13 11:24 UTC, ivargrimstad approved these changes

2021-04-13 11:31 UTC, erdlet commented
> The Jobs are set up since a while back in our Jenkins: https://ci.eclipse.org/krazo/

Yeah you demonstrated ist during the last call :) I added the config there, hopefully correct.

Maybe it makes sense to clean the Travis config in a new PR 🤔

2021-04-13 15:26 UTC, chkal approved these changes
Wow! We had more CXF workarounds in our codebase than I was aware of. Happy to see them being removed. :+1:

2021-04-13 16:08 UTC, Daniel-Dos approved these changes

2021-04-15 07:19 UTC, gtudan approved these changes

2021-04-17 08:08 UTC, erdlet commented
I'll merge this now, so we can see if something is broken. Thanks for your reviews :beers:

2021-04-17 08:08 UTC, merged