Jinja2 ViewEngine extension
eclipse-ee4j/krazo pull request #274
Opened 2021-10-18 19:34 UTC by jelemux

Hello everyone!

So I played a bit around with Krazo and wanted to try and write my own ViewEngine.
Since there wasn't any Jinja2 ViewEngine yet, I wrote this one.

If you like it, you can merge it. If not, I'll probably put this into its own seperate repository for people to find.
Tell me what you think.

2021-10-19 05:07 UTC, erdlet commented
Hi @jelemux,

thanks a lot for the PR. A Jinja2 engine for Krazo is a great addition to the existing ones.

I'll have a deeper look into the code within the next days, hopefully until friday.

2021-10-19 05:10 UTC, erdlet commented
@chkal I think this requires a CQ, right?

2021-10-19 06:20 UTC, ivargrimstad commented
> @chkal I think this requires a CQ, right?

Correct.
I ran the dash-licenses tool and found the following dependencies that need a CQ:

```
krazo/ext/jinja2$ mvn dependency:list | grep -Poh "\S+:(system|provided|compile)" | sort | uniq -> maven.deps
krazo/ext/jinja2$ java -jar ~/Development/eclipse/dash-licenses/core/target/org.eclipse.dash.licenses-0.0.1-SNAPSHOT.jar maven.deps
[main] INFO Querying Eclipse Foundation for license data for 19 items.
[main] INFO Found 10 items.
[main] INFO Querying ClearlyDefined for license data for 9 items.
[main] INFO Found 9 items.
License information could not be automatically verified for the following content:

maven/mavencentral/com.google.code.findbugs/annotations/3.0.1
maven/mavencentral/com.hubspot.jinjava/jinjava/2.5.2
maven/mavencentral/org.jsoup/jsoup/1.10.3

This content is either not correctly mapped by the system, or requires review.
```

2021-10-19 09:52 UTC, erdlet commented
@ivargrimstad thanks for the check.

I'll try to open them this evening.

2021-10-19 10:06 UTC, erdlet requested changes

2021-10-19 10:06 UTC, erdlet commented on ext/jinja2/src/main/resources/LICENSE.txt
> +
I think you can remove this, as the top level project contains the Apache in its LICENSE file.

2021-10-19 10:06 UTC, erdlet commented on ext/pom.xml
> +        <!--        <module>thymeleaf</module>-->
Can you please remove this new whitespace?

2021-10-19 10:06 UTC, erdlet commented on testsuite/src/main/java/org/eclipse/krazo/test/ext/jinja2/HelloController.java
> + * HelloController test.
Please remove this unnecessary JavaDoc

2021-10-19 10:06 UTC, erdlet commented on testsuite/src/main/java/org/eclipse/krazo/test/ext/jinja2/MyApplication.java
> + * Class MyApplication.
Please remove this unnecessary JavaDoc

2021-10-19 10:06 UTC, erdlet commented on ext/jinja2/src/main/java/org/eclipse/krazo/ext/jinja2/Jinja2ViewEngine.java
> +    protected final Jinjava jinjava = new Jinjava();
I'd propose to create `Jinjava` in a separate `Producer` (e.g. like it is done [here](https://github.com/eclipse-ee4j/krazo/blob/master/ext/thymeleaf/src/main/java/org/eclipse/krazo/ext/thymeleaf/DefaultTemplateEngineProducer.java))? 

This way an user can easily overwrite the configuration by using `@Specializes` and doesn't need to extend the whole `ViewEngine`

2021-10-19 11:08 UTC, jelemux commented
Thanks for the review. I think I'll be able to make the changes tomorrow.

2021-10-19 16:20 UTC, jelemux commented
Found a bit of time in-between and made the changes.
Is it ok like that? Would you want me to rebase and squash to create one single commit?

2021-11-04 09:48 UTC, erdlet commented
Hi @jelemux,

please update the dependency on `jinjava` to the latest available version. Version `2.5.2` is more than two years old and there are no Git tags for this version in the GitHub repo. Unfortunately, I need the source for exactly this revision for the CQ. Thanks in advance.

Sorry for the delay, I was on vacation and had no real internet connection there.

2021-11-04 09:49 UTC, erdlet requested changes
Update on `jinjava` required. Was recognized during CQ process.

2021-11-04 13:01 UTC, jelemux commented
I used this version because there was a incompatibility in the dependencies with `guava`. The latest `jinjava` version depends on `guava` version `25.0-jre` and uses the method `com.google.common.collect.ImmutableMap.toImmutableMap` which is not present in the `guava` version imported by `shrinkwrap-resolver-bom` version `3.1.3`. 

Although it seemed the easiest solution at the time, it was not a good idea to just downgrade the `jinjava` version. What I should have done instead (and what I have done now) is upgrade the `shrinkwrap-resolver-bom` version to `3.1.4` (which does not depend on `guava` at all anymore).  
Is this ok for everyone?

2021-11-04 13:04 UTC, erdlet commented
Sounds like a plan, thanks for investigating. Please do the update in a separate PR, because this concerns more modules of Krazo

2021-11-04 13:40 UTC, jelemux commented
Done. Thanks for the quick response!

2021-11-05 12:31 UTC, erdlet commented
Hi @jelemux,
I just merged #275. Can you please rebase this feature branch on the current `master`? I'll create the CQ for Jinjava 2.6.0 and after that we finally should be able to merge this.

2021-11-05 12:36 UTC, erdlet commented
CQ created: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23821

2021-11-05 12:36 UTC, erdlet approved these changes

2021-11-09 08:22 UTC, erdlet commented
CQ seems to be approved. I'll do a last check of the PR this evening and merge it afterwards.

2021-11-10 18:35 UTC, erdlet commented
Hi @jelemux,

I ran the testsuite against different application servers (Glassfish and WildFly) and unfortunately it seems that WildFly 25 has problems with Jinjava. Can you please investigate this problem? My log contains the following root cause:

`Caused by: java.lang.ClassNotFoundException: jinjava.jakarta.el.ExpressionFactory`

Thanks!

2021-11-11 18:27 UTC, jelemux commented
Hi @erdlet, thanks for pointing that out!
I looked into it but I am honestly at a loss.

First of all, it threw a different exception for me: 
`java.lang.NoClassDefFoundError: Failed to link org/eclipse/krazo/test/ext/jinja2/MyApplication (Module "deployment.5b3a22c8-32e8-4c09-a3e6-5baa2469fb1c.war" from Service Module Loader): jakarta/ws/rs/core/Application`

The only clue I have is that if I remove the `IgnoreOnWildfly` classifier from `AsciiDocIT`, it throws the same exception. 
So maybe it's the same problem as with Asciidoctor? The exception is not very specific though, so could be, could be not...

2021-11-15 17:13 UTC, chkal commented
@jelemux First: Thanks a lot for the contribution! :beers: 

> I used this version because there was a incompatibility in the dependencies with `guava`.

I love Guava, but using libraries which depend on different Guava versions is a nightmare. I spent so many hours trying to resolve such issues. :sob: 

> I ran the testsuite against different application servers (Glassfish and WildFly) and unfortunately it seems that WildFly 25 has problems with Jinjava.

@erdlet If the test is green on Glassfish, then maybe it would be fine to use `@IgnoreOnWildfly` for now? We could file a new issue to diagnose this issue later.

2021-11-15 17:37 UTC, erdlet commented
Yes, I think we can do this for now. I guess the problem is, as most of the time, namespace switch related. But let's investigate this in an separate issue.

2021-11-16 07:38 UTC, erdlet commented
@jelemux can you please just add the `@IgnoreOnWildfly` annotation on this test and open an separate issue? After that I'll merge the PR as it has worked at least on Glassfish on my machine.

2021-11-17 17:49 UTC, merged

2021-11-27 11:48 UTC, chkal commented
I finally find some time to work off all the mail notifications I got in the last weeks.

@jelemux Thanks a lot for your contribution. Great work! :beers: